### ISSUE TITLE
하위

### ISSUE THREAD

**Issue by bactoria** [ohjuntaek/ohjuntaek#1]
![image](https://user-images.githubusercontent.com/25674959/99072661-ccea7780-25f7-11eb-9f50-4b994cb5591c.png)

움짤 테스트

**Comment by bactoria** [comment]
움짤 테스트 결과: 이미지가 움직이지않음. 
~CleanShot 괜히 샀음.~

CleanShot 으로 이미지 움직이기 가능함. 저때 움짤이 왜 안움직인지 모르겠으나,
다른 곳에서 되는것 확인함.

**Comment by ohjuntaek** [comment]
확인
